-- Campos adicionais para Controle de Carga (NewOxxy)
ALTER TABLE "Pedido" ADD COLUMN IF NOT EXISTS "onda"         INTEGER DEFAULT 1;
ALTER TABLE "Pedido" ADD COLUMN IF NOT EXISTS "subRegiao"    TEXT;
ALTER TABLE "Pedido" ADD COLUMN IF NOT EXISTS "periodo"      TEXT DEFAULT 'MANHA'; -- MANHA | TARDE | NOITE
ALTER TABLE "Pedido" ADD COLUMN IF NOT EXISTS "aurCargaOk"   BOOLEAN DEFAULT FALSE;
ALTER TABLE "Pedido" ADD COLUMN IF NOT EXISTS "liberadoEm"   TIMESTAMP;
ALTER TABLE "Pedido" ADD COLUMN IF NOT EXISTS "volumes"      INTEGER DEFAULT 0;
ALTER TABLE "Pedido" ADD COLUMN IF NOT EXISTS "pesoKg"       DECIMAL(10,3) DEFAULT 0;
ALTER TABLE "Pedido" ADD COLUMN IF NOT EXISTS "regiao"       TEXT;
ALTER TABLE "Pedido" ADD COLUMN IF NOT EXISTS "bairro"       TEXT;
ALTER TABLE "Pedido" ADD COLUMN IF NOT EXISTS "cep"          TEXT;
ALTER TABLE "Pedido" ADD COLUMN IF NOT EXISTS "statusCarga"  TEXT DEFAULT 'IMPRESSO';
-- IMPRESSO | IMPRESSAO_PENDENTE | PEDIDO_ALTERADO | AURCARGA_OK | FINALIZADO

ALTER TABLE "Romaneio" ADD COLUMN IF NOT EXISTS "periodo"    TEXT DEFAULT 'MANHA';
ALTER TABLE "Romaneio" ADD COLUMN IF NOT EXISTS "onda"       INTEGER DEFAULT 1;
ALTER TABLE "Romaneio" ADD COLUMN IF NOT EXISTS "horaInicio" TEXT; -- ex: "07:30"
ALTER TABLE "Romaneio" ADD COLUMN IF NOT EXISTS "slaPercent" DECIMAL(5,2) DEFAULT 0;
ALTER TABLE "Romaneio" ADD COLUMN IF NOT EXISTS "qtdEntregas" INTEGER DEFAULT 0;

-- Tipo de veículo mais detalhado
ALTER TABLE "Veiculo" ADD COLUMN IF NOT EXISTS "refrigerado" BOOLEAN DEFAULT FALSE;
ALTER TABLE "Veiculo" ADD COLUMN IF NOT EXISTS "motoristaNome" TEXT;
